version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "08:00"
    timezone: America/Denver
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.13.15
  - dependency-name: webpack
    versions:
    - 5.30.0
    - 5.32.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.13.12
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.4
    - 6.1.0
    - 6.2.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.22.0
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.2
    - 6.0.4
    - 6.1.0
    - 6.2.2
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: history
    versions:
    - 5.0.0
  - dependency-name: npm
    versions:
    - 7.5.4
    - 7.6.0
  - dependency-name: ejs
    versions:
    - 3.1.6
  - dependency-name: lodash
    versions:
    - 4.17.21
  rebase-strategy: disabled
  registries:
  - npm-registry-npm-pkg-github-com
